# Generated by Django 5.2.7 on 2025-10-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_assureur', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'Assureur")),
            ],
            options={
                'verbose_name': 'Assureur',
                'verbose_name_plural': 'Assureurs',
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('type_proprietaire', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('assureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assureur')),
            ],
            options={
                'verbose_name': 'Assurance Navire',
                'verbose_name_plural': 'Assurances Navires',
            },
        ),
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_navire', models.CharField(max_length=200)),
                ('num_immatricule', models.CharField(max_length=100, unique=True)),
                ('imo', models.CharField(blank=True, max_length=50, verbose_name='IMO')),
                ('mmsi', models.CharField(blank=True, max_length=50, verbose_name='MMSI')),
                ('type_navire', models.CharField(max_length=100)),
                ('lieu_de_construction', models.CharField(blank=True, max_length=150)),
                ('annee_de_construction', models.PositiveIntegerField(blank=True, null=True)),
                ('nature_coque', models.CharField(blank=True, choices=[('Bois', 'Bois'), ('Contreplaqué', 'Contreplaqué'), ('Fer', 'Fer'), ('Acier', 'Acier'), ('Aluminium', 'Aluminium'), ('Plastique', 'Plastique'), ('Fibre de verre', 'Fibre de verre'), ('Polyester', 'Polyester'), ('Composite', 'Composite'), ('Caoutchouc', 'Caoutchouc'), ('Pneumatique', 'Pneumatique'), ('Titane', 'Titane')], max_length=100, null=True)),
                ('nbr_passager', models.PositiveIntegerField(default=0)),
                ('nbr_equipage', models.PositiveIntegerField(default=0)),
                ('photo_navire', models.ImageField(blank=True, null=True, upload_to='photos_navires/')),
                ('activites', models.ManyToManyField(blank=True, related_name='navires_pratiquant', to='api.activite')),
                ('assureurs', models.ManyToManyField(related_name='navires_assures', through='api.Assurance', to='api.assureur')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proprietaire')),
            ],
            options={
                'verbose_name': 'Navire',
                'verbose_name_plural': 'Navires',
            },
        ),
        migrations.CreateModel(
            name='Moteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_moteur', models.CharField(max_length=200)),
                ('puissance', models.CharField(help_text='Ex: 200 CV', max_length=50)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moteurs', to='api.navire')),
            ],
            options={
                'verbose_name': 'Moteur',
                'verbose_name_plural': 'Moteurs',
            },
        ),
        migrations.CreateModel(
            name='MetaDonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meta_donne', models.CharField(max_length=100)),
                ('nom_meta_donne', models.CharField(max_length=100)),
                ('valeur_meta_donne', models.CharField(max_length=255)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_donnees', to='api.navire')),
            ],
            options={
                'verbose_name': 'Méta-Donnée',
                'verbose_name_plural': 'Méta-Données',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dossier', models.CharField(max_length=100)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='api.navire')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
            },
        ),
        migrations.AddField(
            model_name='assurance',
            name='navire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.navire'),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('expiration_permis', models.DateField()),
                ('lieu_visite', models.CharField(max_length=200)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='api.navire')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
            },
        ),
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together={('navire', 'assureur', 'date_debut')},
        ),
    ]
