# Generated by Django 5.2.7 on 2025-10-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='metadonne',
            name='type_meta_donne',
            field=models.CharField(max_length=20),
        ),
    ]
