# Generated by Django 5.2.7 on 2025-10-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assurance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='assureur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='api.assureur'),
        ),
    ]
