# Generated by Django 5.2.7 on 2025-10-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assurance_assureur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='navire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='api.navire'),
        ),
    ]
