# Generated by Django 5.2.7 on 2025-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assurance_navire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadonne',
            name='nom_meta_donne',
            field=models.CharField(max_length=100, verbose_name='Nom (Clé)'),
        ),
        migrations.AlterField(
            model_name='metadonne',
            name='type_meta_donne',
            field=models.CharField(choices=[('TEXTE', 'Texte (Court ou Long)'), ('NOMBRE', 'Nombre (Entier ou Décimal)'), ('DATE', 'Date'), ('HEURE', 'Heure (Time)'), ('BOOLEEN', 'Vrai/Faux (Oui/Non)'), ('URL', 'Lien Internet (URL)'), ('FICHIER', 'Fichier (Document)'), ('IMAGE', 'Image (JPG, PNG, etc.)')], default='TEXTE', max_length=20, verbose_name='Type de donnée'),
        ),
        migrations.AlterField(
            model_name='metadonne',
            name='valeur_meta_donne',
            field=models.TextField(blank=True, null=True, verbose_name='Valeur'),
        ),
        migrations.AlterUniqueTogether(
            name='metadonne',
            unique_together={('navire', 'nom_meta_donne')},
        ),
    ]
