# Generated by Django 5.2.7 on 2025-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_metadonne_nom_meta_donne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='type_proprietaire',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('gouvernement', 'Gouvernement'), ('association', 'Association'), ('autre', 'Autre')], default='particulier', max_length=20),
        ),
    ]
