# Generated by Django 5.2.7 on 2025-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_proprietaire_type_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
