# Generated by Django 5.2.7 on 2025-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_proprietaire_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
