# Generated by Django 5.2.7 on 2025-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_proprietaire_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadonne',
            name='valeur_meta_donne',
        ),
        migrations.AddField(
            model_name='metadonne',
            name='fichier_meta_donne',
            field=models.FileField(blank=True, help_text='Utilisé pour les types FICHIER et IMAGE', null=True, upload_to='meta_donnees/fichiers/', verbose_name='Fichier/Image'),
        ),
        migrations.AddField(
            model_name='metadonne',
            name='valeur_texte',
            field=models.TextField(blank=True, help_text='Utilisé pour les types TEXTE, NOMBRE, DATE, HEURE, BOOLEEN, URL', null=True, verbose_name='Valeur Texte'),
        ),
    ]
